### ISSUE TITLE
Consider new pool members inactive by default until the first successful healthcheck

### ISSUE THREAD

**Issue by kayrus** [sapcc/octavia-f5-provider-driver#206]
Creating a new member in a pool with healthchecks instantly activates this member for the traffic, despite member operating_status API result is still OFFLINE or ERROR.

Steps to reproduce:
* create a TCP listener
* create a TCP pool with healthchecks
* create two pool members: one real IP with an http listener, another unreachable
* run curl -I lb_floating_ip -> the success rate is 50%

Expected behavior: LB should not route traffic to a new pool member until the successful healtchcheck verdict.

cc @databus23

**Comment by m-kratochvil** [comment]
Related Slack thread: https://convergedcloud.slack.com/archives/C6HHGQZG8/p1677858951224809
I also had a long discussion with Anton.

@BenjaminLudwigSAP @notandy let's discuss this in the Octavia sync, I can provide the background.

**Comment by m-kratochvil** [comment]
In other words, what this request is asking for:
*  if there is a pool-level health-check monitor applied to a pool, and user adds a pool member to such pool, the Big-IP should not forward traffic to such pool member until the health-check marks the pool member "up".

This is, however, not the default behavior of the Big-IP. When user creates new pool member in a pool with existing pool-level health-check monitor, the pool-member/monitor go immediately into status "checking" and the Big-IP is trying to get a response to the health-check probes, per the monitor configuration. During this time (the health-monitor timeout period), traffic is forwarded to the pool member, because from the Big-IP perspective, the pool member has the same status as if it had no monitor at all. Then if the monitor succeeds, Big-IP continues forwarding traffic to the pool member, and marks it "up", if the monitor fails all the probes, Big-IP stops forwarding traffic to the pool member and marks it "down".

The logic is, the Big-IP considers all pool members are by default "up", as in majority of use-cases that is what the user wants. To create a pool member and not want any traffic forwarded to it, is a corner case, thus not a default behavior.

**What we discussed as possible solutions:**
- creating pool members in disabled state (weight=0), rejected
- lowering a timeout of the health-check from current 180 second to 10 seconds, rejected

As mentioned in my comment above, we can discuss possible solution on Octavia side in the Octavia sync, plus I will run this request past our F5 consultant to see if there is a way to circumvent the default behavior, perhaps with use of an irule.

**Comment by m-kratochvil** [comment]
We have discussed the issue in the Octavia round and agreed to follow up next week, no conclusions yet.
We did agree the "OFFLINE" member status can be misleading in certain situations and we will look into a possibility of changing it to something else, pending upstream Octavia behavior cross-check.

**Comment by notandy** [comment]
I've commented in slack my observations with haproxy/upstream code, so we can continue discussing possible ways of going forward next week.

**Comment by m-kratochvil** [comment]
We have discussed this topic in the octavia group to see whether there is anything that requires correction/modification/refactoring/redesign.
We have (@notandy ) cross-checked the behavior of upstream Octavia and the HAProxy implementation as far as setting member statuses and confirmed it's the same basic logic as our F5 backend has - member is considered live and receiving traffic until the health-check proves otherwise. Changing this would basically mean breaking an expected behavior, plus deviating from upstream. That doesn't mean you can't open an issue in upstream Octavia to request such behavior change, if it's implemented upstream, we will can then consider changing it also in our environment.

For now, there are no changes considered on our end.
