### ISSUE TITLE
iRule seems to use incorrect certificate subject

### ISSUE THREAD

**Issue by simonkowallik** [sapcc/octavia-f5-provider-driver#266]
The iRule name suggests the subject of the client certificate should be used but the command `X509::issuer` extracts the issuer.
This is likely a typo and `X509::subject` was meant to be used.

https://github.com/sapcc/octavia-f5-provider-driver/blob/0ec88b9b7c42c500f966a777144d48a5ff6cbe86/octavia_f5/restclient/as3objects/irule.py#L96

**Comment by m-kratochvil** [comment]
Thanks a lot for reporting this one, I'm checking

**Comment by m-kratochvil** [comment]
I had a look at the `X509::subject` command [documentation](https://clouddocs.f5.com/api/irules/X509__subject.html) and apparently there are two options:

`X509::subject <X509 certificate>`  -  returns the subject of the specified X509 certificate

And from TMOS v16.1.3 also:
`X509::subject <X509 certificate> commonName`  -  returns the subject commonName (CN) found in the specified X509 certificate in UTF8 format

Since majority of our systems are on TMOS v15.1.3 I will propose to use `X509::subject <X509 certificate>` but I'd still like to understand the difference between the two above options. Can you help me out @simonkowallik ?

**Comment by simonkowallik** [comment]
`X509::subject` extracts the whole subject from the x509 certificate structure. The subject is a distinguished name (DN). The common name (CN) might be part of the DN, see: https://www.rfc-editor.org/rfc/rfc5280#section-4.1.2.6

`X509::subject <certificate> commonName` extracts the CN from the subject DN, hence making it easier in case one looks for just the CN. In this particular iRule it could replace the tcl procedure `x509CNExtract` to further simplify and optimize the iRule.

**Comment by m-kratochvil** [comment]
Thanks a lot @simonkowallik for the clarification.
Once all our systems are upgraded to the current GR 17.1.1.1 (or higher) I will open new issue to further optimize the irule.
