### ISSUE TITLE
nlbaas2octavia: Migration from f5-openstack-agent to octavia-f5-provider

### ISSUE THREAD

**Issue by notandy** [sapcc/octavia-f5-provider-driver#52]
We need a working migration path for existing loadbalancers in using the neutron lbaas f5-openstack-agent.

I backported the nlbaas2octavia driver from stein to our queens release: 
https://github.com/sapcc/neutron-lbaas/tree/stable/queens-m3/tools/nlbaas2octavia

Features needed:

- [x] Migration of all lbaas objects
- [x] Migration of neutron listener ports
- [x] Migration of selfip ports and discovering of used / unused selfips
- [x] ~~Migration of ESD policies (if applicable)~~

**Comment by laerlingSAP** [comment]
ESD migration will not be necessary because they are being used unchanged.
The only thing that's changing is that special L7policies won't exist anymore (tags will be used instead), but that doesn't affect ESDs.

Can this issue be closed or do you want to close it after the migration is complete, @notandy?

**Comment by notandy** [comment]
The migration code is not quite finished, woul like to let it open for myself but will delete the task-point, thanks!
